### ISSUE TITLE
## Add a new Player

### ISSUE THREAD

**Issue by anitaschiller** [anitaschiller/soccer-app#1]
### Value Statement:
As a football club customer I want to be able to add a new player to the transfer market so that others can see my offer.

### Complexity: 
L

### Acceptance Criteria:
- [ ] The user can submit the form by clicking on a submit button
- [ ] The user can clear the form by clicking on a cancel button
- [ ] The user should not be able to submit the form if one of the mandatory fields are not properly filled
- [ ] If there is an error in the form, a message should be displayed to inform the user
- [ ] The form should have at least the follwing fields: player name, club, position, price, contact email

### Tasks
- [ ] Create a new form component
- [ ] Make form a controlled component
- [ ] Save the new player in a players array/useState
- [ ] Add propTypes
- [ ] Add Styleguidist
